server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/IdeaProjects/UserCRUD/config-repo
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9555/eureka
